# Generated by Django 3.1.4 on 2021-01-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spacegroup',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=25)),
                ('hall', models.CharField(max_length=25)),
                ('point_group', models.CharField(max_length=25)),
                ('crystal_system', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'spacegroups',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=200)),
                ('formula', models.CharField(max_length=50)),
                ('formation_energy', models.FloatField()),
                ('natom', models.IntegerField()),
                ('element_list', models.CharField(max_length=25)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
                ('generic', models.CharField(default='', max_length=25)),
                ('volume', models.FloatField(default=0.0)),
                ('nelement', models.IntegerField(default=0)),
                ('spacegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.spacegroup')),
            ],
            options={
                'db_table': 'entries',
            },
        ),
    ]
